coverage:
  precision: 2
  round: down
  range: "80..100"

  status:
    project:
      default:
        target: 90%
        threshold: 1%
    patch:
      default:
        target: 95%
        threshold: 0%

comment:
  layout: "header, diff"
  behavior: default
  require_changes: true

ignore:
  - "tests/*"
  - "htmlcov/*"
  - "dist/*"
  - ".venv/*"
